name: EpicKits
main: Main.Main
version: 3.5
author: zPandaKST
commands:
  kit:
  kits:
  build:
  head:
  help:  
  gm:
  tell:    
  tp:  
  warps:
  fisherman:
  inv:    
  spawn:
  bc:
  sumo:
  report:    
  fps:
  challenge:
  main:   
  admin:     
  tags:
  tag:       
  arena:
  tpall: 
  met: 
  SetArena:
  staff:
  ajuda:    
  coins:
  togglepvp:
  ping:
  tphere:
  morrer:
  monitorar:
  admins:
  monitorgui:
  visgui:
  invis:
  vis:
  givekit:
  manutencao:
  givepermission:
  skit:
  chat:
  atualizar:
  sortearkit:
  sortearvip:
  promover:
  givevip:
  groupset:
  removepermission:
  permissionslist:
  removevip:
  removekit:
  score:
  perfil:
  autosoup:
  aplicar:
  kits2:
  setmotd:
  xp:
  upar:
  loja:
  regras:
  stafflist:
     aliases: [suicide]    
  voar:
     aliases: [fly]
  youtuber:
     aliases: [yt]     
  clearchat:
     aliases: [cc]
  testclick:
     aliases: [ct]